name: portal_ui_kit
description: A reusable UI kit with configurable themes, including a retro theme inspired by nes.css.
version: 0.0.2
homepage: https://github.com/tanvoid0/portal_ui_kit

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.portal_ui_kit
        pluginClass: PortalUiKitPlugin
      ios:
        pluginClass: PortalUiKitPlugin
      web:
        pluginClass: PortalUiKitWeb
        fileName: portal_ui_kit_web.dart